import type { ColorScheme } from '@/types/color';
import { rgbToHex } from '../color/conversion';

/**
 * Generates a Ghostty terminal color scheme configuration file.
 *
 * :param scheme: The color scheme to export.
 * :param name: Name of the color scheme for the header comment.
 * :returns: Ghostty .conf file content as a string.
 */
export function generateGhosttyConf(scheme: ColorScheme, name: string): string {
    const { ansi, ui } = scheme;

    const template = `
# Ghostty Color Scheme: ${name}
# Generated by Termicolor (https://termicolor.io)

# ANSI palette (colors 0-15)
palette = 0=%%color0.hex%%
palette = 1=%%color1.hex%%
palette = 2=%%color2.hex%%
palette = 3=%%color3.hex%%
palette = 4=%%color4.hex%%
palette = 5=%%color5.hex%%
palette = 6=%%color6.hex%%
palette = 7=%%color7.hex%%
palette = 8=%%color8.hex%%
palette = 9=%%color9.hex%%
palette = 10=%%color10.hex%%
palette = 11=%%color11.hex%%
palette = 12=%%color12.hex%%
palette = 13=%%color13.hex%%
palette = 14=%%color14.hex%%
palette = 15=%%color15.hex%%

# Base colors
background = %%background.hex%%
foreground = %%foreground.hex%%

# Cursor
cursor-color = %%cursor.hex%%
cursor-text = %%cursor-text.hex%%

# Selection (use color8/7 for muted contrast)
selection-background = %%selection.hex%%
selection-foreground = %%selection-text.hex%%
`

    return template
        // ANSI colors
        .replace(/%%color0\.hex%%/g, rgbToHex(ansi.black))
        .replace(/%%color1\.hex%%/g, rgbToHex(ansi.red))
        .replace(/%%color2\.hex%%/g, rgbToHex(ansi.green))
        .replace(/%%color3\.hex%%/g, rgbToHex(ansi.yellow))
        .replace(/%%color4\.hex%%/g, rgbToHex(ansi.blue))
        .replace(/%%color5\.hex%%/g, rgbToHex(ansi.magenta))
        .replace(/%%color6\.hex%%/g, rgbToHex(ansi.cyan))
        .replace(/%%color7\.hex%%/g, rgbToHex(ansi.white))
        .replace(/%%color8\.hex%%/g, rgbToHex(ansi.brightBlack))
        .replace(/%%color9\.hex%%/g, rgbToHex(ansi.brightRed))
        .replace(/%%color10\.hex%%/g, rgbToHex(ansi.brightGreen))
        .replace(/%%color11\.hex%%/g, rgbToHex(ansi.brightYellow))
        .replace(/%%color12\.hex%%/g, rgbToHex(ansi.brightBlue))
        .replace(/%%color13\.hex%%/g, rgbToHex(ansi.brightMagenta))
        .replace(/%%color14\.hex%%/g, rgbToHex(ansi.brightCyan))
        .replace(/%%color15\.hex%%/g, rgbToHex(ansi.brightWhite))

        // UI colors
        .replace(/%%background\.hex%%/g, rgbToHex(ui.background))
        .replace(/%%foreground\.hex%%/g, rgbToHex(ui.foreground))
        .replace(/%%cursor\.hex%%/g, rgbToHex(ui.cursor))
        .replace(/%%cursor-text\.hex%%/g, rgbToHex(ui.cursorText))
        .replace(/%%selection\.hex%%/g, rgbToHex(ui.selection))
        .replace(/%%selection-text\.hex%%/g, rgbToHex(ui.selectionText));
}
