/**
 * Hyper terminal color scheme exporter.
 */

import type { ColorScheme, ANSIColorName } from '@/types/color';
import { rgbToHex } from '../color/conversion';

/**
 * Maps internal ANSI color names to Hyper's color property names.
 *
 * Hyper uses "light" prefix for bright colors (e.g., lightBlack, lightRed)
 * instead of "bright" prefix.
 */
const HYPER_COLOR_MAP: Record<ANSIColorName, string> = {
  black: 'black',
  red: 'red',
  green: 'green',
  yellow: 'yellow',
  blue: 'blue',
  magenta: 'magenta',
  cyan: 'cyan',
  white: 'white',
  brightBlack: 'lightBlack',
  brightRed: 'lightRed',
  brightGreen: 'lightGreen',
  brightYellow: 'lightYellow',
  brightBlue: 'lightBlue',
  brightMagenta: 'lightMagenta',
  brightCyan: 'lightCyan',
  brightWhite: 'lightWhite',
};

/**
 * Generates a Hyper terminal color scheme configuration file.
 *
 * :param scheme: The color scheme to export.
 * :param name: The name of the color scheme.
 * :returns: JavaScript module string for Hyper configuration.
 */
export function generateHyperConfig(scheme: ColorScheme, name: string): string {
  const foreground = rgbToHex(scheme.ui.foreground);
  const background = rgbToHex(scheme.ui.background);
  const cursor = rgbToHex(scheme.ui.cursor);
  const selection = rgbToHex(scheme.ui.selection);

  // Build the colors object entries
  const colorEntries = Object.entries(HYPER_COLOR_MAP)
    .map(([ansiName, hyperName]) => {
      const color = scheme.ansi[ansiName as ANSIColorName];
      const hex = rgbToHex(color);
      return `      ${hyperName}: '${hex}',`;
    })
    .join('\n');

  return `// Hyper Color Scheme: ${name}
// Generated by Termicolor (https://termicolor.io)
//
// USAGE: Copy the properties below into your ~/.hyper.js config object.
// Add these inside the existing 'config: { ... }' section.

module.exports = {
  config: {
    // Add these color settings to your .hyper.js config:
    foregroundColor: '${foreground}',
    backgroundColor: '${background}',
    cursorColor: '${cursor}',
    selectionColor: '${selection}80',
    colors: {
${colorEntries}
    },
  },
};
`;
}

/**
 * Downloads a Hyper color scheme file.
 *
 * :param scheme: The color scheme to download.
 * :param name: The name of the color scheme.
 */
export function downloadHyperConfig(scheme: ColorScheme, name: string): void {
  const content = generateHyperConfig(scheme, name);
  const blob = new Blob([content], { type: 'application/javascript' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = `${name.toLowerCase().replace(/\s+/g, '-')}.hyper.js`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);
}
