import { describe, it, expect } from 'vitest';
import { generateHyperConfig } from './hyper';
import type { ColorScheme } from '@/types/color';

const TEST_SCHEME: ColorScheme = {
  ansi: {
    black: { r: 0, g: 0, b: 0 },
    red: { r: 255, g: 0, b: 0 },
    green: { r: 0, g: 255, b: 0 },
    yellow: { r: 255, g: 255, b: 0 },
    blue: { r: 0, g: 0, b: 255 },
    magenta: { r: 255, g: 0, b: 255 },
    cyan: { r: 0, g: 255, b: 255 },
    white: { r: 255, g: 255, b: 255 },
    brightBlack: { r: 128, g: 128, b: 128 },
    brightRed: { r: 255, g: 128, b: 128 },
    brightGreen: { r: 128, g: 255, b: 128 },
    brightYellow: { r: 255, g: 255, b: 128 },
    brightBlue: { r: 128, g: 128, b: 255 },
    brightMagenta: { r: 255, g: 128, b: 255 },
    brightCyan: { r: 128, g: 255, b: 255 },
    brightWhite: { r: 255, g: 255, b: 255 },
  },
  ui: {
    background: { r: 30, g: 30, b: 30 },
    foreground: { r: 220, g: 220, b: 220 },
    cursor: { r: 255, g: 255, b: 255 },
    cursorText: { r: 0, g: 0, b: 0 },
    selection: { r: 100, g: 100, b: 200 },
    selectionText: { r: 255, g: 255, b: 255 },
    badge: { r: 255, g: 0, b: 0 },
  },
};

describe('generateHyperConfig', () => {
  it('generates header comment with scheme name', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'My Theme');

    expect(config).toContain('// Hyper Color Scheme: My Theme');
    expect(config).toContain('// Generated by Termicolor');
  });

  it('includes usage instructions', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    expect(config).toContain('USAGE');
    expect(config).toContain('.hyper.js');
  });

  it('exports as module', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    expect(config).toContain('module.exports = {');
    expect(config).toContain('config: {');
  });

  it('includes UI colors', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    expect(config).toContain("foregroundColor: '#dcdcdc'");
    expect(config).toContain("backgroundColor: '#1e1e1e'");
    expect(config).toContain("cursorColor: '#ffffff'");
  });

  it('includes selection color with alpha', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    // Selection color should have 80 alpha appended
    expect(config).toContain("selectionColor: '#6464c880'");
  });

  it('includes colors object with all ANSI colors', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    expect(config).toContain('colors: {');
    expect(config).toContain("black: '#000000'");
    expect(config).toContain("red: '#ff0000'");
    expect(config).toContain("green: '#00ff00'");
    expect(config).toContain("yellow: '#ffff00'");
    expect(config).toContain("blue: '#0000ff'");
    expect(config).toContain("magenta: '#ff00ff'");
    expect(config).toContain("cyan: '#00ffff'");
    expect(config).toContain("white: '#ffffff'");
  });

  it('uses lightX naming for bright colors (Hyper convention)', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    expect(config).toContain("lightBlack: '#808080'");
    expect(config).toContain("lightRed: '#ff8080'");
    expect(config).toContain("lightGreen: '#80ff80'");
    expect(config).toContain("lightYellow: '#ffff80'");
    expect(config).toContain("lightBlue: '#8080ff'");
    expect(config).toContain("lightMagenta: '#ff80ff'");
    expect(config).toContain("lightCyan: '#80ffff'");
    expect(config).toContain("lightWhite: '#ffffff'");
  });

  it('does not use brightX naming', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    // Hyper uses "light" prefix, not "bright"
    expect(config).not.toContain('brightBlack:');
    expect(config).not.toContain('brightRed:');
  });

  it('generates valid JavaScript syntax', () => {
    const config = generateHyperConfig(TEST_SCHEME, 'Test');

    // Should have proper trailing commas and structure
    expect(config).toContain("black: '#000000',");
    expect(config).toContain('},');
    expect(config).toContain('};');
  });
});
